### PR TITLE
UI changes and defect fix

### PR DESCRIPTION
**Pull request by jasonwzs**
- change panel display name to 'SAML'
- add toggle button support in toolbar including corresponding styles
- simply the panel view:
  - remove 'Method' and 'Status' columns in request list view
  - remove URL display from request detail view
  - remove 'Unfomatted SAML' view, reuse CodeMirror view for both SAML display formats
  - add toggle button 'SAML Format' for switching between the two SAML display formats
  - change 'SAML Filter' to toggle button, by default the request list only shows SAML traffic
- refine css style to make the panel view look more consistent with Chrome's devtool style:
  - add css class on request views according to response status (for future use)
  - remove the option regarding to number of spaces for indent, use default option
  - fix a typo in css file on a 'max-width' value
  - adjust the table layout and row height
  - adjust the font
  - adjust some paddings/margins
  - add word-wrap on CodeMirror view
- fix some defects:
  - do not show the requests to chrome extension resources (i.e. URL
    starts from 'chrome-extension://')
  - fix auto scrolling issue when showing only SAML traffic and after changing the filter setting
  - fix request detail tab switching issue, keep selected tab if it is present on both current and previous selected requests

### CODE REVIEW

**Comment by jasonwzs** [comment]
Here are the screenshots with the change in this pull request:
image
image
image

**Comment by jasonwzs** [comment]
@milton-lai , I find this chrome extension you implement and find it is very useful. I think the UI can be improved, to make it simpler and more consistent with Chrome's built-in views, so I fork your repository and expect these changes can be merged back to your repository.
Note that this pull request also contains some bug fixes that I find during testing.
Let me know if you have any concern/comment. 
If you don't want to merge this pull request, let me know  if you agree that I can publish my work on chrome web store by creating a new extension based on your work. Thanks!

**Comment by milton-lai** [comment]
Hey @jasonwzs, thanks for looking into this and great work! I'll have a quick test now and will deploy soon =). I'll note your changes in the release notes.

**Comment by milton-lai** [comment]
@jasonwzs was there a purpose for removing the HTTP status and response? I find that it is useful to know what type of request/response it is.

**Comment by milton-lai** [comment]
@jasonwzs - I've added back the 2 columns that were removed as I think it provides some extra functionality. Maybe we'll look to remove the 2 columns as part of some settings. I noticed that the colour's don't work for the 2xx/3xx/else. I've added some code to set the row to BOLD if it is a SAML record. This might help down the track with setting colours for different HTTP codes.

I've also deployed the latest version to the store now and credited!
Thanks again!
Milton

**Comment by jasonwzs** [comment]
@milton-lai , thanks for the quick review and response. Terrific!
Here is my though why I removed the two columns: I think for the users of this extension, the major use case is to quickly find out which requests are SAML related requests (which is also the reason why 'show only SAML requests' is default setting) and get the decoded SAML XML for selected request. User can always see the status and method in 'Request' detail tab if they need to know. Removing the two columns makes the list view looks cleaner.
But I agree it's better to add some other indicator on the request list rows according to whether it is SAML related request and the response status. The codes I added for 2xx/3xx/else can be used for different styles, e.g. we can add a little ball 'icon' with different colors on the beginning of the request row: green for 2xx, orange for 3xx, red for 4xx/5xx. For SAML related request, my suggestion is when the filter setting is to show all we give those SAML rows a different background color to highlight it.
Let me know what you think.

**Pull request merged**
